-- 027 rollback: exempts the owner from the policies again.
-- WARNING: this disables tenant isolation for the owning application role.

ALTER TABLE appointments     NO FORCE ROW LEVEL SECURITY;
ALTER TABLE assignments      NO FORCE ROW LEVEL SECURITY;
ALTER TABLE availabilities   NO FORCE ROW LEVEL SECURITY;
ALTER TABLE blog_categories  NO FORCE ROW LEVEL SECURITY;
ALTER TABLE blog_posts       NO FORCE ROW LEVEL SECURITY;
ALTER TABLE lessons          NO FORCE ROW LEVEL SECURITY;
ALTER TABLE payment_events   NO FORCE ROW LEVEL SECURITY;
ALTER TABLE payments         NO FORCE ROW LEVEL SECURITY;
ALTER TABLE projects         NO FORCE ROW LEVEL SECURITY;
ALTER TABLE refunds          NO FORCE ROW LEVEL SECURITY;
ALTER TABLE services         NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sites            NO FORCE ROW LEVEL SECURITY;
ALTER TABLE students         NO FORCE ROW LEVEL SECURITY;
ALTER TABLE tenant_modules   NO FORCE ROW LEVEL SECURITY;
ALTER TABLE tenant_tools     NO FORCE ROW LEVEL SECURITY;
ALTER TABLE users            NO FORCE ROW LEVEL SECURITY;
ALTER TABLE websites         NO FORCE ROW LEVEL SECURITY;
