// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"sen duzeltır mısın lutfen 
)

// Student defines model for Student.
type Student struct {
	Email     openapi_types.Email `json:"email"`
	FirstName string              `json:"first_name"`
	Id        openapi_types.UUID  `json:"id"`
	LastName  string              `json:"last_name"`
}

// StudentCreate defines model for StudentCreate.
type StudentCreate struct {
	Email     openapi_types.Email `json:"email"`
	FirstName string              `json:"first_name"`
	LastName  string              `json:"last_name"`
}

// PostStudentsJSONRequestBody defines body for PostStudents for application/json ContentType.
type PostStudentsJSONRequestBody = StudentCreate
