FROM golang:1.23-alpine

RUN go install github.com/air-verse/air@latest && \
    apk add --no-cache git ca-certificates

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN air init

EXPOSE 8080
CMD ["air", "-c", ".air.toml"]