FROM golang:1.25-alpine

# Install dependencies: air for hot-reloading, git and ca-certificates for go modules, curl for downloading migrate
RUN go install github.com/air-verse/air@latest && \
    apk add --no-cache git ca-certificates curl

# Install golang-migrate
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.1/migrate.linux-amd64.tar.gz | tar xvz && \
    mv migrate.linux-amd64 /usr/local/bin/migrate && \
    chmod +x /usr/local/bin/migrate

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

# Install golang-migrate
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

COPY . .

EXPOSE 8080
CMD ["air", "-c", ".air.toml"]