basePath: /
host: localhost:8080
info:
  contact:
    email: support@nexspaces.com
    name: API Support
    url: https://www.nexspaces.com/support
  description: This is a production-ready multi-tenant SaaS backend built with modern
    Clean Architecture + DDD patterns.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: NexSpaces API
  version: "1.0"
paths: {}
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
